#!/usr/bin/env node
/**
 * Generate the initial migrations from docs/mysql/schema.sql.
 *
 * Plan days 6-7. Generated rather than hand-copied: 15 tables of DDL
 * transcribed by hand is a reliable source of silent column-type errors, and
 * a wrong DECIMAL scale is not something a test would catch later.
 *
 * Re-run after Phase 0 reconciles schema.sql against the live database.
 *
 * Two decisions are applied here, both of which change every table:
 *
 * 1. OPTIMISTIC CONCURRENCY -> `row_version INT UNSIGNED NOT NULL DEFAULT 1`
 *
 *    Legacy compared every original column value plus @IsNull_* flags on each
 *    UPDATE/DELETE (plan 2.5). A naive `WHERE uid = ?` would convert today's
 *    concurrency violations into silent overwrites (11.4).
 *
 *    Chosen over `updated_at`: two updates inside the same clock tick are
 *    indistinguishable by timestamp, and clock skew across app instances makes
 *    it worse. A monotonic counter has neither problem.
 *
 *    Chosen over reproducing whole-row comparison: that is fragile around NULL
 *    handling and DECIMAL equality, and produces enormous WHERE clauses for no
 *    benefit over a counter.
 *
 *    NOT adding created_at/updated_at. There is no source data for them, so
 *    every migrated row would claim to have been created at migration time.
 *    Fabricated timestamps in a financial system are worse than absent ones.
 *
 * 2. COLLATION -> storage stays `utf8mb4_unicode_ci`; display order is done in
 *    Go with x/text/collate for zh.
 *
 *    Legacy sorts under Chinese_PRC_CI_AS (pinyin). MySQL's closest analogue
 *    is utf8mb4_zh_0900_as_cs, but that is accent- AND case-sensitive, which
 *    would silently change equality semantics for permission values (读写) and
 *    the 是否* string columns that the app compares by value. Changing sort
 *    order is a display bug; changing equality is a correctness bug.
 *
 *    So: keep case-insensitive equality, sort for display in the application.
 *    `ORDER BY carseries` in SQL is NOT authoritative for display order.
 *
 * Foreign keys are emitted as a SEPARATE migration, not part of 0001. Plan 5.3
 * requires validating the legacy data for orphans before adding them, and that
 * cannot happen until cmd/migrate-data has run.
 */

import fs from "node:fs";
import path from "node:path";

const SCHEMA = "docs/mysql/schema.sql";
const OUT = "migrations";

const sql = fs.readFileSync(SCHEMA, "utf8");

// ---------------------------------------------------------------------------
// Parse
// ---------------------------------------------------------------------------

const tables = [];
for (const m of sql.matchAll(/CREATE TABLE `(\w+)` \(([\s\S]*?)\n\) ENGINE=[^;]*;/g)) {
  tables.push({ name: m[1], body: m[2] });
}

const foreignKeys = [];
for (const m of sql.matchAll(/ALTER TABLE `(\w+)`\s+ADD CONSTRAINT[^;]*;/g)) {
  foreignKeys.push(m[0].trim());
}

if (tables.length === 0) {
  console.error(`no CREATE TABLE found in ${SCHEMA}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

const banner = `-- Generated by tools/gen-migration/gen.mjs from ${SCHEMA}.
-- Do not hand-edit: re-run the generator instead.
--
-- !! DERIVED FROM AN INFERRED SCHEMA !!
-- docs/mysql/schema.sql is reconstructed from CmsDB.xsd, which cannot express
-- DEFAULT values, indexes, CHECK constraints, triggers, computed columns, or
-- the real collation. Everything marked TODO(phase0) below is a known gap that
-- docs/mssql-export.sql must fill before this runs against anything but a
-- scratch database.
`;

const upTables = tables
  .map(({ name, body }) => {
    // Insert row_version immediately before the PRIMARY KEY clause so it reads
    // as a table-level concern rather than a business column.
    const lines = body.split("\n");
    const pkIdx = lines.findIndex((l) => /PRIMARY KEY/.test(l));
    const rowVersion =
      "  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 " +
      "COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',";
    if (pkIdx >= 0) lines.splice(pkIdx, 0, rowVersion);
    else lines.push(rowVersion.replace(/,$/, ""));

    return (
      `DROP TABLE IF EXISTS \`${name}\`;\n` +
      `CREATE TABLE \`${name}\` (\n${lines.join("\n")}\n` +
      `) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`
    );
  })
  .join("\n\n");

const up = `${banner}
-- TODO(phase0): confirm COLUMN_DEFAULT for every column      (export step 4)
-- TODO(phase0): confirm NULL/NOT NULL against INFORMATION_SCHEMA (step 4)
-- TODO(phase0): add non-PK indexes — none are known yet      (step 6)
-- TODO(phase0): add CHECK constraints, if any exist          (step 8)
-- TODO(phase0): confirm the source collation                 (step 10)
--
-- Indexes are the most consequential gap. Every non-clustered index on the
-- source is a query the old system depended on for performance; rediscovering
-- them under production load is the expensive way to find out.

SET NAMES utf8mb4;

${upTables}
`;

const down = `${banner}
-- Drops every table created by 0001. Order is irrelevant while no foreign
-- keys exist (they arrive in 0002), but FOREIGN_KEY_CHECKS is disabled anyway
-- so this stays correct if 0002 has been applied.

SET FOREIGN_KEY_CHECKS = 0;

${tables
  .map((t) => `DROP TABLE IF EXISTS \`${t.name}\`;`)
  .reverse()
  .join("\n")}

SET FOREIGN_KEY_CHECKS = 1;
`;

const fkUp = `${banner}
-- Foreign keys, applied AFTER cmd/migrate-data has loaded the legacy data and
-- reported zero orphans per relationship.
--
-- Deliberately separate from 0001. Plan 5.3: years of unconstrained operation
-- make dangling references likely, and a migration that fails halfway through
-- adding constraints leaves a half-constrained schema. Load first, verify,
-- then constrain.
--
-- tbl_storechange.onroadid is implied by the vw_* joins but was never declared
-- in the source. It is included here because the port needs the guarantee;
-- expect it to be the relationship most likely to have orphans.

${foreignKeys.length ? foreignKeys.join("\n") : "-- TODO(phase0): no FK statements found in the schema file"}
`;

// Derived from the ALTER TABLE statements above, so the two files cannot drift.
const fkDropStatements = foreignKeys
  .map((stmt) => {
    const table = stmt.match(/ALTER TABLE `(\w+)`/)?.[1];
    const name = stmt.match(/ADD CONSTRAINT `(\w+)`/)?.[1];
    return table && name
      ? `ALTER TABLE \`${table}\` DROP FOREIGN KEY \`${name}\`;`
      : null;
  })
  .filter(Boolean)
  .reverse(); // mirror image of the up file

const fkDown = `${banner}
-- Drops the constraints added by 0002, in reverse order.
--
-- Generated from 0002's own ALTER TABLE statements, so the pair cannot drift.
-- A down migration that silently does nothing is worse than none: a rollback
-- appears to succeed while leaving the schema constrained.

${fkDropStatements.length ? fkDropStatements.join("\n") : "-- no foreign keys to drop"}
`;

fs.mkdirSync(OUT, { recursive: true });
const files = {
  "0001_init.up.sql": up,
  "0001_init.down.sql": down,
  "0002_foreign_keys.up.sql": fkUp,
  "0002_foreign_keys.down.sql": fkDown,
};
for (const [name, content] of Object.entries(files)) {
  fs.writeFileSync(path.join(OUT, name), content);
}

// ---------------------------------------------------------------------------

const columnCount = tables.reduce(
  (n, t) => n + t.body.split("\n").filter((l) => /^\s*`/.test(l)).length,
  0,
);

console.log(`source        : ${SCHEMA}`);
console.log(`tables        : ${tables.length}`);
console.log(`columns       : ${columnCount} (+${tables.length} row_version)`);
console.log(`foreign keys  : ${foreignKeys.length} (deferred to 0002)`);
console.log(`\nwrote:\n${Object.keys(files).map((f) => `  ${OUT}/${f}`).join("\n")}`);
