-- Generated by tools/gen-migration/gen.mjs from docs/mysql/schema.sql.
-- Do not hand-edit: re-run the generator instead.
--
-- !! DERIVED FROM AN INFERRED SCHEMA !!
-- docs/mysql/schema.sql is reconstructed from CmsDB.xsd, which cannot express
-- DEFAULT values, indexes, CHECK constraints, triggers, computed columns, or
-- the real collation. Everything marked TODO(phase0) below is a known gap that
-- docs/mssql-export.sql must fill before this runs against anything but a
-- scratch database.

-- TODO(phase0): confirm COLUMN_DEFAULT for every column      (export step 4)
-- TODO(phase0): confirm NULL/NOT NULL against INFORMATION_SCHEMA (step 4)
-- TODO(phase0): add non-PK indexes — none are known yet      (step 6)
-- TODO(phase0): add CHECK constraints, if any exist          (step 8)
-- TODO(phase0): confirm the source collation                 (step 10)
--
-- Indexes are the most consequential gap. Every non-clustered index on the
-- source is a query the old system depended on for performance; rediscovering
-- them under production load is the expensive way to find out.

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `tbl_userinfo`;
CREATE TABLE `tbl_userinfo` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `departmentcode` VARCHAR(50) NOT NULL,
  `departmentname` VARCHAR(100) NULL,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_cartype`;
CREATE TABLE `tbl_cartype` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `carseries` VARCHAR(100) NOT NULL,
  `carcode` VARCHAR(50) NOT NULL,
  `carname` VARCHAR(200) NOT NULL,
  `eop` VARCHAR(50) NOT NULL,
  `subsets` VARCHAR(50) NULL,
  `insidesetcode` VARCHAR(50) NULL,
  `insidesetname` VARCHAR(100) NULL,
  `inprice` DECIMAL(10,2) NOT NULL,
  `outprice` DECIMAL(10,2) NOT NULL,
  `otherprice1` DECIMAL(10,2) NOT NULL,
  `otherprice2` DECIMAL(10,2) NOT NULL,
  `otherprice3` DECIMAL(10,2) NOT NULL,
  `otherprice4` DECIMAL(10,2) NOT NULL,
  `propval` DECIMAL(10,2) NOT NULL,
  `profitval` DECIMAL(10,3) NOT NULL,
  `outstoreprice` DECIMAL(10,3) NOT NULL,
  `vinprefix` VARCHAR(50) NOT NULL,
  `enginenoprefix` VARCHAR(50) NOT NULL,
  `deleted` SMALLINT NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_dbbackup_log`;
CREATE TABLE `tbl_dbbackup_log` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(200) NOT NULL,
  `backupdate` DATETIME NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_env`;
CREATE TABLE `tbl_env` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_onroad`;
CREATE TABLE `tbl_onroad` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `billno` VARCHAR(50) NOT NULL,
  `billdate` DATETIME NOT NULL,
  `vin` VARCHAR(50) NOT NULL,
  `engineno` VARCHAR(50) NOT NULL,
  `cartypeid` INT NOT NULL,
  `cartype` VARCHAR(50) NOT NULL,
  `carname` VARCHAR(200) NULL,
  `colorcode` VARCHAR(50) NULL,
  `colorname` VARCHAR(100) NULL,
  `subsets` VARCHAR(50) NULL,
  `insidesetcode` VARCHAR(50) NULL,
  `insidesetname` VARCHAR(100) NULL,
  `carstate` VARCHAR(50) NULL,
  `property` VARCHAR(50) NULL,
  `inprice` DECIMAL(10,2) NULL,
  `inflag` SMALLINT NOT NULL,
  `inkind` SMALLINT NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`),
  KEY `idx_tbl_onroad_cartypeid` (`cartypeid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_permission`;
CREATE TABLE `tbl_permission` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `userinfoid` INT NOT NULL,
  `fieldname` VARCHAR(50) NOT NULL,
  `permission` VARCHAR(50) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`),
  KEY `idx_tbl_permission_userinfoid` (`userinfoid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_stats`;
CREATE TABLE `tbl_stats` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `statsdate` VARCHAR(50) NOT NULL,
  `companyname` VARCHAR(100) NOT NULL,
  `bonus1` DECIMAL(10,2) NOT NULL,
  `bonus2` DECIMAL(10,2) NOT NULL,
  `bonus3` DECIMAL(10,2) NOT NULL,
  `bonus4` DECIMAL(10,2) NOT NULL,
  `bonus5` DECIMAL(10,2) NOT NULL,
  `bonus6` DECIMAL(10,2) NOT NULL,
  `bonus7` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_basedata`;
CREATE TABLE `tbl_basedata` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `keyname` VARCHAR(100) NULL,
  `value` VARCHAR(100) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_storein`;
CREATE TABLE `tbl_storein` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `batchno` VARCHAR(50) NOT NULL,
  `storeplace` VARCHAR(50) NOT NULL,
  `onroadid` INT NOT NULL,
  `indate` DATETIME NOT NULL,
  `inprice` DECIMAL(10,2) NOT NULL,
  `passno` VARCHAR(50) NOT NULL,
  `companyno` SMALLINT NOT NULL,
  `inpath` VARCHAR(100) NOT NULL,
  `intype` VARCHAR(100) NOT NULL,
  `incarpricekind` VARCHAR(50) NOT NULL,
  `factoryoutdate` DATETIME NOT NULL,
  `repairstate` VARCHAR(100) NULL,
  `reservestate` VARCHAR(100) NULL,
  `propval` DECIMAL(10,2) NOT NULL,
  `profitprop` DECIMAL(10,2) NOT NULL,
  `profitval` DECIMAL(10,3) NOT NULL,
  `specprofitval` DECIMAL(10,2) NOT NULL,
  `profitstate` VARCHAR(50) NOT NULL,
  `outstoreprice` DECIMAL(10,3) NOT NULL,
  `settlementname` VARCHAR(50) NOT NULL,
  `handlername` VARCHAR(50) NOT NULL,
  `remark` VARCHAR(500) NULL,
  `outflag` SMALLINT NULL,
  `changedate` DATETIME NOT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`),
  KEY `idx_tbl_storein_onroadid` (`onroadid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_storeout`;
CREATE TABLE `tbl_storeout` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `batchno` VARCHAR(50) NOT NULL,
  `onroadid` INT NOT NULL,
  `salecompany` VARCHAR(100) NOT NULL,
  `outbillno` VARCHAR(50) NOT NULL,
  `salekind` VARCHAR(50) NOT NULL,
  `settlementname` VARCHAR(50) NOT NULL,
  `handlername` VARCHAR(50) NOT NULL,
  `saleplace` VARCHAR(50) NOT NULL,
  `incarkind` VARCHAR(100) NOT NULL,
  `outdate` DATETIME NOT NULL,
  `customername` VARCHAR(50) NOT NULL,
  `customerphoneno` VARCHAR(50) NULL,
  `customerjobkind` VARCHAR(50) NOT NULL,
  `saleregion` VARCHAR(100) NOT NULL,
  `customeraddress` VARCHAR(100) NULL,
  `carno` VARCHAR(50) NOT NULL,
  `carspeckind` VARCHAR(50) NULL,
  `isreport` VARCHAR(50) NULL,
  `votecost` DECIMAL(10,2) NOT NULL,
  `inprice` DECIMAL(10,2) NULL,
  `otherprice1` DECIMAL(10,2) NULL,
  `otherprice2` DECIMAL(10,2) NULL,
  `otherprice3` DECIMAL(10,2) NULL,
  `otherprice4` DECIMAL(10,2) NULL,
  `interestprice` DECIMAL(10,2) NULL,
  `profitval` DECIMAL(10,2) NULL,
  `specprofitval` DECIMAL(10,2) NULL,
  `outprice` DECIMAL(10,2) NOT NULL,
  `pricediff` DECIMAL(10,2) NULL,
  `isbill` VARCHAR(50) NULL,
  `billoutdate` DATETIME NULL,
  `ispayment` VARCHAR(50) NULL,
  `paymentdate` DATETIME NULL,
  `issend` VARCHAR(50) NULL,
  `senddate` DATETIME NULL,
  `remark` VARCHAR(500) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`),
  KEY `idx_tbl_storeout_onroadid` (`onroadid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_quarterstats`;
CREATE TABLE `tbl_quarterstats` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `carseries` VARCHAR(50) NULL,
  `type` TINYINT UNSIGNED NULL,
  `total1` INT NULL,
  `total2` INT NULL,
  `total3` INT NULL,
  `total4` INT NULL,
  `m1` INT NULL,
  `m2` INT NULL,
  `m3` INT NULL,
  `m4` INT NULL,
  `m5` INT NULL,
  `m6` INT NULL,
  `m7` INT NULL,
  `m8` INT NULL,
  `m9` INT NULL,
  `m10` INT NULL,
  `m11` INT NULL,
  `m12` INT NULL,
  `remain1` INT NULL,
  `remain2` INT NULL,
  `remain3` INT NULL,
  `remain4` INT NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_carcompany`;
CREATE TABLE `tbl_carcompany` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `companyno` SMALLINT NOT NULL,
  `companyname` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `postno` VARCHAR(100) NULL,
  `telno` VARCHAR(100) NULL,
  `cartypes` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `managername` VARCHAR(100) NULL,
  `linkmanname` VARCHAR(100) NULL,
  `property` VARCHAR(100) NULL,
  `remark` VARCHAR(500) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_log`;
CREATE TABLE `tbl_log` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `logdate` DATETIME NOT NULL,
  `title` VARCHAR(50) NULL,
  `cont` VARCHAR(200) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_storechange`;
CREATE TABLE `tbl_storechange` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `changeid` INT NOT NULL,
  `batchno` VARCHAR(50) NOT NULL,
  `onroadid` INT NOT NULL,
  `storeplace` VARCHAR(100) NOT NULL,
  `actionkind` VARCHAR(50) NOT NULL,
  `actiondate` DATETIME NOT NULL,
  `actionpay` DECIMAL(10,2) NOT NULL,
  `settlementname` VARCHAR(50) NOT NULL,
  `handlername` VARCHAR(50) NOT NULL,
  `repairstate` VARCHAR(100) NULL,
  `reservestate` VARCHAR(100) NULL,
  `remark` VARCHAR(500) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`),
  KEY `idx_tbl_storechange_onroadid` (`onroadid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tbl_fit`;
CREATE TABLE `tbl_fit` (

  `uid` INT NOT NULL AUTO_INCREMENT,
  `consumer` VARCHAR(50) NOT NULL,
  `seller` VARCHAR(50) NULL,
  `fitdate` DATETIME NULL,
  `fitprice` DECIMAL(10,2) NULL,
  `remark` VARCHAR(100) NULL,
  `row_version` INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'optimistic concurrency; mismatch -> 409 Conflict',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
