-- Generated by tools/gen-migration/gen.mjs from docs/mysql/schema.sql.
-- Do not hand-edit: re-run the generator instead.
--
-- !! DERIVED FROM AN INFERRED SCHEMA !!
-- docs/mysql/schema.sql is reconstructed from CmsDB.xsd, which cannot express
-- DEFAULT values, indexes, CHECK constraints, triggers, computed columns, or
-- the real collation. Everything marked TODO(phase0) below is a known gap that
-- docs/mssql-export.sql must fill before this runs against anything but a
-- scratch database.

-- Drops every table created by 0001. Order is irrelevant while no foreign
-- keys exist (they arrive in 0002), but FOREIGN_KEY_CHECKS is disabled anyway
-- so this stays correct if 0002 has been applied.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `tbl_fit`;
DROP TABLE IF EXISTS `tbl_storechange`;
DROP TABLE IF EXISTS `tbl_log`;
DROP TABLE IF EXISTS `tbl_carcompany`;
DROP TABLE IF EXISTS `tbl_quarterstats`;
DROP TABLE IF EXISTS `tbl_storeout`;
DROP TABLE IF EXISTS `tbl_storein`;
DROP TABLE IF EXISTS `tbl_basedata`;
DROP TABLE IF EXISTS `tbl_stats`;
DROP TABLE IF EXISTS `tbl_permission`;
DROP TABLE IF EXISTS `tbl_onroad`;
DROP TABLE IF EXISTS `tbl_env`;
DROP TABLE IF EXISTS `tbl_dbbackup_log`;
DROP TABLE IF EXISTS `tbl_cartype`;
DROP TABLE IF EXISTS `tbl_userinfo`;

SET FOREIGN_KEY_CHECKS = 1;
