-- Generated by tools/gen-migration/gen.mjs from docs/mysql/schema.sql.
-- Do not hand-edit: re-run the generator instead.
--
-- !! DERIVED FROM AN INFERRED SCHEMA !!
-- docs/mysql/schema.sql is reconstructed from CmsDB.xsd, which cannot express
-- DEFAULT values, indexes, CHECK constraints, triggers, computed columns, or
-- the real collation. Everything marked TODO(phase0) below is a known gap that
-- docs/mssql-export.sql must fill before this runs against anything but a
-- scratch database.

-- Foreign keys, applied AFTER cmd/migrate-data has loaded the legacy data and
-- reported zero orphans per relationship.
--
-- Deliberately separate from 0001. Plan 5.3: years of unconstrained operation
-- make dangling references likely, and a migration that fails halfway through
-- adding constraints leaves a half-constrained schema. Load first, verify,
-- then constrain.
--
-- tbl_storechange.onroadid is implied by the vw_* joins but was never declared
-- in the source. It is included here because the port needs the guarantee;
-- expect it to be the relationship most likely to have orphans.

ALTER TABLE `tbl_permission`
  ADD CONSTRAINT `fk_tbl_permission_userinfoid`
  FOREIGN KEY (`userinfoid`) REFERENCES `tbl_userinfo` (`uid`);
ALTER TABLE `tbl_onroad`
  ADD CONSTRAINT `fk_tbl_onroad_cartypeid`
  FOREIGN KEY (`cartypeid`) REFERENCES `tbl_cartype` (`uid`);
ALTER TABLE `tbl_storein`
  ADD CONSTRAINT `fk_tbl_storein_onroadid`
  FOREIGN KEY (`onroadid`) REFERENCES `tbl_onroad` (`uid`);
ALTER TABLE `tbl_storeout`
  ADD CONSTRAINT `fk_tbl_storeout_onroadid`
  FOREIGN KEY (`onroadid`) REFERENCES `tbl_onroad` (`uid`);
ALTER TABLE `tbl_storechange`
  ADD CONSTRAINT `fk_tbl_storechange_onroadid`
  FOREIGN KEY (`onroadid`) REFERENCES `tbl_onroad` (`uid`);
