-- Generated by tools/gen-migration/gen.mjs from docs/mysql/schema.sql.
-- Do not hand-edit: re-run the generator instead.
--
-- !! DERIVED FROM AN INFERRED SCHEMA !!
-- docs/mysql/schema.sql is reconstructed from CmsDB.xsd, which cannot express
-- DEFAULT values, indexes, CHECK constraints, triggers, computed columns, or
-- the real collation. Everything marked TODO(phase0) below is a known gap that
-- docs/mssql-export.sql must fill before this runs against anything but a
-- scratch database.

-- Drops the constraints added by 0002, in reverse order.
--
-- Generated from 0002's own ALTER TABLE statements, so the pair cannot drift.
-- A down migration that silently does nothing is worse than none: a rollback
-- appears to succeed while leaving the schema constrained.

ALTER TABLE `tbl_storechange` DROP FOREIGN KEY `fk_tbl_storechange_onroadid`;
ALTER TABLE `tbl_storeout` DROP FOREIGN KEY `fk_tbl_storeout_onroadid`;
ALTER TABLE `tbl_storein` DROP FOREIGN KEY `fk_tbl_storein_onroadid`;
ALTER TABLE `tbl_onroad` DROP FOREIGN KEY `fk_tbl_onroad_cartypeid`;
ALTER TABLE `tbl_permission` DROP FOREIGN KEY `fk_tbl_permission_userinfoid`;
