-- vw_onroad — PROVISIONAL, reconcile against the Phase 0 dump.
--
-- Hand-written; must not be regenerated by tools/gen-migration/gen.mjs.
--
-- WHAT IS KNOWN
-- docs/mysql/schema.sql §3 records the exact column contract: the 18 columns of
-- tbl_onroad plus `carseries`. carseries lives on tbl_cartype, and
-- tbl_onroad.cartypeid -> tbl_cartype.uid is a declared foreign key, so the
-- shape of the join is not in doubt.
--
-- WHAT IS NOT KNOWN, AND WHY IT MATTERS
-- Whether the original used INNER or LEFT JOIN. That is not cosmetic:
--
--   INNER — an on-road vehicle whose cartypeid is orphaned VANISHES from every
--           screen and report built on this view.
--   LEFT  — it appears, with a NULL carseries.
--
-- Plan §5.3 expects orphans ("years of unconstrained operation make dangling
-- references likely"), so the two can genuinely differ on real data.
--
-- LEFT JOIN is used here deliberately. If the original was INNER, this shows
-- extra rows, which is visible and reported. If it was LEFT and this used
-- INNER, rows would disappear silently — and silent row loss in a financial
-- system is the worse failure by a wide margin.
--
-- TODO(phase0): replace with the dumped definition. If it turns out to be
-- INNER, decide explicitly whether to reproduce that or to keep LEFT and fix
-- the orphans — do not let the choice happen by default.

CREATE OR REPLACE VIEW `vw_onroad` AS
SELECT
  o.`uid`,
  o.`billno`,
  o.`billdate`,
  o.`vin`,
  o.`engineno`,
  o.`cartypeid`,
  o.`cartype`,
  o.`carname`,
  o.`colorcode`,
  o.`colorname`,
  o.`subsets`,
  o.`insidesetcode`,
  o.`insidesetname`,
  o.`carstate`,
  o.`property`,
  o.`inprice`,
  o.`inflag`,
  o.`inkind`,
  c.`carseries`
FROM `tbl_onroad` o
LEFT JOIN `tbl_cartype` c ON c.`uid` = o.`cartypeid`;
