-- vw_storein and vw_storeout — PROVISIONAL, reconcile against the Phase 0 dump.
--
-- Hand-written; must not be regenerated by tools/gen-migration/gen.mjs.
--
-- WHAT IS KNOWN
-- docs/mysql/schema.sql §3 records the exact column list each view must expose,
-- name for name and in order, because the Go repositories and the report code
-- are written against them. Both are reproduced here exactly: 42 columns for
-- vw_storein, 55 for vw_storeout.
--
-- The joins are not in doubt either: tbl_storein.onroadid -> tbl_onroad.uid and
-- tbl_onroad.cartypeid -> tbl_cartype.uid are both declared foreign keys, and
-- `carseries` exists only on tbl_cartype.
--
-- WHAT IS NOT KNOWN
-- Whether the originals used INNER or LEFT. Same judgement as migration 0005:
-- LEFT here deliberately. An INNER original means this shows extra rows, which
-- is visible and reported; a LEFT original reproduced as INNER means rows
-- vanish silently, and silent row loss in a financial system is far worse.
--
-- `Expr1` in vw_storeout is an unnamed computed expression in the original and
-- its formula is NOT recoverable from this repo. It is exposed as NULL so the
-- column name and arity survive — anything consuming it gets an obviously wrong
-- value rather than a subtly wrong one, and the migration does not silently
-- drop a column the report code may select.
--
-- TODO(phase0): replace both with the dumped definitions, and recover what
-- Expr1 actually computes.

CREATE OR REPLACE VIEW `vw_storein` AS
SELECT
  s.`uid`, s.`batchno`, s.`storeplace`, s.`onroadid`, s.`indate`, s.`inprice`,
  s.`passno`, s.`companyno`, s.`inpath`, s.`intype`, s.`incarpricekind`,
  s.`factoryoutdate`, s.`repairstate`, s.`reservestate`, s.`propval`,
  s.`profitprop`, s.`profitval`, s.`specprofitval`, s.`profitstate`,
  s.`outstoreprice`, s.`settlementname`, s.`handlername`, s.`remark`, s.`outflag`,
  o.`billno`, o.`billdate`, o.`vin`, o.`engineno`, o.`cartypeid`, o.`cartype`,
  o.`carname`, o.`colorcode`, o.`subsets`, o.`colorname`, o.`insidesetcode`,
  o.`insidesetname`, o.`carstate`, o.`property`, o.`inflag`, o.`inkind`,
  s.`changedate`, c.`carseries`
FROM `tbl_storein` s
LEFT JOIN `tbl_onroad`  o ON o.`uid` = s.`onroadid`
LEFT JOIN `tbl_cartype` c ON c.`uid` = o.`cartypeid`;

CREATE OR REPLACE VIEW `vw_storeout` AS
SELECT
  t.`uid`, t.`onroadid`, t.`batchno`, t.`salecompany`, t.`outbillno`, t.`salekind`,
  t.`settlementname`, t.`handlername`, t.`saleplace`, t.`incarkind`, t.`outdate`,
  t.`customername`, t.`customerphoneno`, t.`customerjobkind`, t.`saleregion`,
  t.`customeraddress`, t.`carno`, t.`carspeckind`, t.`isreport`, t.`votecost`,
  t.`inprice`, t.`otherprice1`, t.`otherprice2`, t.`otherprice3`, t.`otherprice4`,
  t.`interestprice`, t.`profitval`, t.`outprice`, t.`pricediff`, t.`isbill`,
  t.`billoutdate`, t.`ispayment`, t.`paymentdate`, t.`issend`, t.`senddate`,
  t.`remark`,
  o.`billno`, o.`billdate`, o.`vin`, o.`cartypeid`, o.`engineno`, o.`cartype`,
  o.`carname`, o.`colorcode`, o.`colorname`, o.`subsets`, o.`insidesetcode`,
  o.`insidesetname`, o.`carstate`, o.`property`,
  NULL AS `Expr1`,
  o.`inflag`, o.`inkind`, t.`specprofitval`, c.`carseries`
FROM `tbl_storeout` t
LEFT JOIN `tbl_onroad`  o ON o.`uid` = t.`onroadid`
LEFT JOIN `tbl_cartype` c ON c.`uid` = o.`cartypeid`;
