-- vw_speccar — PROVISIONAL, reconcile against the Phase 0 dump.
--
-- Hand-written; must not be regenerated by tools/gen-migration/gen.mjs.
--
-- WHAT IS KNOWN
-- docs/mysql/schema.sql §3 records the exact 53-column contract, reproduced
-- here name for name and in order. Every column comes from tbl_storeout or
-- tbl_onroad — unlike vw_storein/vw_storeout there is no `carseries`, so
-- tbl_cartype is not joined at all.
--
-- WHAT IS NOT KNOWN, AND THE JUDGEMENT MADE
-- Whether the original view FILTERS to special vehicles. Its name says it
-- should, and FrmSpecCar re-applies `salekind = '大客户'` when opening the edit
-- dialog (FrmSpecCar.cs:327,331) — which reads either as belt-and-braces over
-- an already-filtered view, or as the only filter there is.
--
-- Against that: FrmSpecCar.LoadTableFromDB clears the binding filter and Fills
-- the whole view (lines 89-91), then shows every row it gets. If the view
-- filtered, that grid would already be special-cars-only.
--
-- NO filter is applied here, same principle as the INNER/LEFT decision in 0005
-- and 0006: if the original filtered, this shows extra rows, which is visible
-- and reported. If it did not and this filtered, rows would vanish silently.
-- The `salekind` predicate is instead applied by the repository allowlist and
-- defaulted in the UI, where it is visible and adjustable.
--
-- TODO(phase0): replace with the dumped definition. If it does filter, move
-- the predicate here and drop the UI default.

CREATE OR REPLACE VIEW `vw_speccar` AS
SELECT
  t.`uid`, t.`batchno`, t.`onroadid`, t.`salecompany`, t.`outbillno`, t.`salekind`,
  t.`settlementname`, t.`handlername`, t.`saleplace`, t.`incarkind`, t.`outdate`,
  t.`customername`, t.`customerphoneno`, t.`customerjobkind`, t.`saleregion`,
  t.`customeraddress`, t.`carno`, t.`carspeckind`, t.`isreport`, t.`votecost`,
  t.`inprice`, t.`otherprice1`, t.`otherprice2`, t.`otherprice3`, t.`otherprice4`,
  t.`interestprice`, t.`profitval`, t.`specprofitval`, t.`outprice`, t.`pricediff`,
  t.`isbill`, t.`billoutdate`, t.`ispayment`, t.`paymentdate`, t.`issend`,
  t.`senddate`, t.`remark`,
  o.`billno`, o.`billdate`, o.`vin`, o.`engineno`, o.`cartypeid`, o.`cartype`,
  o.`carname`, o.`colorcode`, o.`colorname`, o.`subsets`, o.`insidesetcode`,
  o.`insidesetname`, o.`carstate`, o.`property`, o.`inkind`, o.`inflag`
FROM `tbl_storeout` t
LEFT JOIN `tbl_onroad` o ON o.`uid` = t.`onroadid`;
