package auth

import "testing"

// Vectors for DES-CBC/PKCS#7 with key "123456AB" and IV 1234567890ABCDEF,
// generated by python-cryptography and independently confirmed byte-for-byte
// by `openssl enc -des-cbc -provider legacy`.
//
// Neither generator is the implementation under test, which is the point:
// a self-consistent round-trip would pass even if the key derivation, IV or
// padding were wrong. Getting any of those wrong means every existing user is
// locked out on cutover day, and the failure would look like "bad password"
// rather than like a bug.
//
// .NET's DESCryptoServiceProvider defaults to CBC + PKCS#7, so agreement with
// two standards-conformant implementations is agreement with the legacy app.
var legacyVectors = []struct{ plaintext, ciphertext string }{
	{"", "Am7QCxAHl3s="},
	{"123456", "SrIyfqk3hjo="},
	{"admin", "gMNRQJL4Zkw="},
	{"password", "3G6E0xYbz/9rcBgwNecrDg=="},
	{"12345678", "GwmULY6gXBlwduVi7k0MQw=="}, // exact block multiple -> full extra padding block
	{"abcdefghi", "yWzNT9mP2kM+EzNynoid0Q=="},
	{"张三", "Bweq0AIZQCY="}, // UTF-8 multibyte
	{"P@ssw0rd!", "vD84UyUBPdkepbbss4LAoA=="},
	{"口令123", "Wq4M/4LhUJiXksGJrRiX/Q=="}, // mixed CJK + ASCII
}

func TestLegacyDESEncodeMatchesIndependentImplementations(t *testing.T) {
	for _, v := range legacyVectors {
		got, err := legacyDESEncode(v.plaintext)
		if err != nil {
			t.Fatalf("legacyDESEncode(%q): %v", v.plaintext, err)
		}
		if got != v.ciphertext {
			t.Errorf("legacyDESEncode(%q)\n got  %q\n want %q", v.plaintext, got, v.ciphertext)
		}
	}
}

func TestLegacyDESRoundTrip(t *testing.T) {
	for _, v := range legacyVectors {
		got, err := legacyDESDecode(v.ciphertext)
		if err != nil {
			t.Fatalf("legacyDESDecode(%q): %v", v.ciphertext, err)
		}
		if got != v.plaintext {
			t.Errorf("legacyDESDecode(%q) = %q, want %q", v.ciphertext, got, v.plaintext)
		}
	}
}

// The fixed IV makes the legacy scheme deterministic: two users with the same
// password have identical stored ciphertext. Pinned as documentation of the
// weakness being migrated away from, not as a property worth keeping.
func TestLegacyIsDeterministic(t *testing.T) {
	a, _ := legacyDESEncode("hunter2")
	b, _ := legacyDESEncode("hunter2")
	if a != b {
		t.Fatal("expected the legacy scheme to be deterministic")
	}
}

func TestLegacyDecodeRejectsGarbage(t *testing.T) {
	for _, bad := range []string{
		"not base64 at all!",
		"",
		"YWJj",     // valid base64, not a block multiple
		"AAAAAAAA", // block multiple, but invalid padding after decryption
	} {
		if _, err := legacyDESDecode(bad); err == nil {
			t.Errorf("legacyDESDecode(%q) should have failed", bad)
		}
	}
}

// ---------------------------------------------------------------------------

func TestVerifyLegacyPathSignalsUpgrade(t *testing.T) {
	stored, err := legacyDESEncode("s3cret")
	if err != nil {
		t.Fatal(err)
	}
	c := Credential{Legacy: stored}

	ok, upgrade := Verify("s3cret", c)
	if !ok {
		t.Error("correct password rejected on the legacy path")
	}
	if !upgrade {
		t.Error("legacy authentication must signal needsUpgrade so the caller re-hashes")
	}

	if ok, _ := Verify("wrong", c); ok {
		t.Error("wrong password accepted on the legacy path")
	}
}

func TestVerifyBcryptPathDoesNotSignalUpgrade(t *testing.T) {
	hash, err := HashPassword("s3cret")
	if err != nil {
		t.Fatal(err)
	}
	c := Credential{Bcrypt: hash}

	ok, upgrade := Verify("s3cret", c)
	if !ok {
		t.Error("correct password rejected on the bcrypt path")
	}
	if upgrade {
		t.Error("bcrypt authentication must not request an upgrade")
	}

	if ok, _ := Verify("wrong", c); ok {
		t.Error("wrong password accepted on the bcrypt path")
	}
}

// Once a user is upgraded, the legacy column is cleared. Belt and braces: even
// if a stale legacy value survived, bcrypt must take precedence -- otherwise
// clearing the column becomes load-bearing for security.
func TestBcryptTakesPrecedenceOverLegacy(t *testing.T) {
	hash, _ := HashPassword("new-password")
	legacy, _ := legacyDESEncode("old-password")

	c := Credential{Bcrypt: hash, Legacy: legacy}

	if ok, _ := Verify("old-password", c); ok {
		t.Error("the legacy password must not work once a bcrypt hash exists")
	}
	if ok, _ := Verify("new-password", c); !ok {
		t.Error("the bcrypt password should work")
	}
}

func TestVerifyEmptyCredentialAlwaysFails(t *testing.T) {
	if ok, up := Verify("anything", Credential{}); ok || up {
		t.Error("an empty credential must never authenticate")
	}
}

func TestHashPasswordIsSaltedAndVerifiable(t *testing.T) {
	a, err := HashPassword("same-password")
	if err != nil {
		t.Fatal(err)
	}
	b, _ := HashPassword("same-password")

	if a == b {
		t.Error("bcrypt hashes of the same password must differ — salting is the whole point")
	}
	if ok, _ := Verify("same-password", Credential{Bcrypt: b}); !ok {
		t.Error("a freshly generated hash failed to verify")
	}
}

// The test suite lowers the cost for speed (see export_test.go); this guards
// the value production actually uses, so the override cannot silently become
// the real setting.
func TestHashPasswordUsesProductionCost(t *testing.T) {
	if BcryptCost != 12 {
		t.Errorf("BcryptCost = %d, want 12", BcryptCost)
	}
	if BcryptCost <= 10 {
		t.Error("BcryptCost must exceed bcrypt.DefaultCost")
	}
}
